-- Mastiraja Database Schema

-- 1. Create mastiraja_categories table
CREATE TABLE IF NOT EXISTS mastiraja_categories (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create mastiraja_videos table
CREATE TABLE IF NOT EXISTS mastiraja_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES mastiraja_categories(id),
    title TEXT NOT NULL,
    img TEXT,
    video_id TEXT,
    stream_url TEXT,
    post_date TEXT,
    post_time TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(title, category_id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_mastiraja_videos_category ON mastiraja_videos(category_id);
CREATE INDEX IF NOT EXISTS idx_mastiraja_videos_title ON mastiraja_videos(title);
