
-- 1. Create mydesi_categories table
CREATE TABLE IF NOT EXISTS mydesi_categories (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create mydesi_videos table
CREATE TABLE IF NOT EXISTS mydesi_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES mydesi_categories(id),
    title TEXT NOT NULL,
    img TEXT,
    video_id TEXT, -- Extracted video ID (e.g., from DoodStream, Vooe)
    stream_url TEXT, -- Constructed or direct link
    post_date TEXT,
    post_time TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(title, category_id)
);

-- Optional: Add index for faster searching
CREATE INDEX IF NOT EXISTS idx_mydesi_videos_category ON mydesi_videos(category_id);
CREATE INDEX IF NOT EXISTS idx_mydesi_videos_title ON mydesi_videos(title);
