-- 2. Create XNXXVIDEOS Table
CREATE TABLE IF NOT EXISTS xnxxvideos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category_id BIGINT,
    category_name TEXT,
    stream_url TEXT,
    img TEXT,
    post_date TEXT,
    post_time TEXT,
    post_date_raw TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(title, category_id)
);

-- 3. Create Function to Get Unique Categories
CREATE OR REPLACE FUNCTION get_xnxx_unique_categories()
RETURNS TABLE (category_id BIGINT, category_name TEXT) 
LANGUAGE sql 
AS $$
  SELECT DISTINCT category_id, category_name
  FROM xnxxvideos
  WHERE category_id IS NOT NULL;
$$;
